spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT:6379}

naver:
  location:
    search-base-url: ${NAVER_LOCATION_BASE_URL:https://openapi.naver.com}
    search-client-id: ${NAVER_LOCATION_CLIENT_ID}
    search-client-secret: ${NAVER_LOCATION_CLIENT_SECRET}
    maps-base-url: ${NAVER_MAPS_BASE_URL:https://maps.apigw.ntruss.com}
    maps-client-id: ${NAVER_MAPS_CLIENT_ID}
    maps-client-secret: ${NAVER_MAPS_CLIENT_SECRET}
